version: "3.9"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/docker_swarm/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:files/static
    ports:
      - 80:80
  externship:
    image: externship-image:1
    networks:
      - network
    volumes:
      - static-volume: /var/www/externship/backend/ecommerce/static
    secrets:
      - DJANGO_SECRET_KEY
      - DATABASES_HOST
      - DATABASES_NAME
      - DATABASES_USER
      - DATABASES_PASSWORD
      - DATABASES_PORT
      - ALGORITHM
      - KAKAO_CLIENT_ID
      - PHONE_NUMBER
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_ADDRESS
      - AWS_REGION
      - AWS_S3_HOST
      - AWS_BUCKET_NAME
